Breast Cancer QA: Summary for All Sites
=======================================

Generated `r Sys.Date()`

```{r libraries}
library(RSQLite)
```

```{r previous results}
load("bc_fetch_results.RData")  # REDCap table listing of dataset file stats
load("bc_terms_results.RData")  # i2b2 BCcohort query terms
```

```{r shared transformation routines}
source('bc_qa_txform.R')  # Library of stuff
```


Summary of Submissions
======================

```{r fetch, echo=FALSE, results='asis'}
ht(fetch$dataset[, c('site', 'name', 'record_id', 'timestamp')])
```


Collect Exclusion Criteria Data Elements from Each Site
=======================================================

```{r site.code}
site.code <- factor(fetch$dataset$site)  # Provides factor of site code identifiers
```

```{r rbind.sites}
# move to bc_qa_txform.R?
# Produces dataframe which is 'union' of all site-specific datasets

rbind.sites <- function(df.site) {
  df <- NULL
  for (ix in 1:length(site.code)) {
    site <- site.code[ix]

    x <- df.site[[site]]

    if (nrow(x) > 0) {
      x$site <- site
      names <- names(x)
      if (is.null(df)) {
        df <- x
        } else {
          df <- rbind(df, x)
          }
      }
    }
  df
}
```

```{r tumor.all}
# Produces a list of site-specific dataframes
site.tumor.data <- lapply(site.code, function(s) {
  message('working on site: ', s)
  bc.exclusions(fetch$site.data(s))  # Produces site-specific results file
  })
names(site.tumor.data) <- levels(site.code)

```

Apply Exclusion Criteria
========================


```{r}
site.survey.sample <- lapply(site.code, function(s) {
  message('working on site: ', s)
  check.cases(site.tumor.data[[s]])
  })
names(site.survey.sample) <- levels(site.code)
site.survey.sample.size <- lapply(site.code, function(s) {
  count.cases(site.survey.sample[[s]])
  })

names(site.survey.sample.size) <- levels(site.code)
site.survey.sample.size
```

Save for Later Sections
=======================

```{r}
save(site.survey.sample.size, file="bc_excl_all_results.RData")
```
