# Breast Cancer - Sample Cohort
```{r echo=FALSE}
# ============================================================================
###  Generates file of randomized eligible patients
# Input Dataframes
#   dataset       - desriptors for site's input dataset 
#   tumor.site    - pt tumors listing
#   survey.sample - complex frame created by bc_excl

# Considerations (Potential Enhancements)
#    - Writes file to fetch$dataDir (~/GPC-Development/bc-data-files)
#    - Rates are embedded and could be loaded from an external file
# 
# Note - script was modeled after 'multitumor.rmd'
#
# ============================================================================
```

```{r Initialize settings and libraries, echo=FALSE}
# library(ggplot2)
library(reshape)

# Don't wrap so much
options(width=300)
opts_chunk$set(echo=FALSE)
```


```{r Load BC functions}
source('bc_qa_txform.R')  
```

### Load specified sampling rates for GPC sites 

```{r}
# Rates as of 4-Mar BC Conf Call
# site.sample.rates <-       data.frame(site="KUMC",    rate=0.4)
# site.sample.rates <- rbind(site.sample.rates, 
#                            data.frame(site="MCRF",    rate=0.75))
# site.sample.rates <- rbind(site.sample.rates, 
#                            data.frame(site="MCW",     rate=0.75))
# site.sample.rates <- rbind(site.sample.rates, 
#                            data.frame(site="UIOWA",   rate=100))
# site.sample.rates <- rbind(site.sample.rates, 
#                            data.frame(site="UMN",     rate=0.55))
# site.sample.rates <- rbind(site.sample.rates, 
#                            data.frame(site="UNMC",    rate=100))
# site.sample.rates <- rbind(site.sample.rates, 
#                            data.frame(site="UTHSCSA", rate=100))
# site.sample.rates <- rbind(site.sample.rates, 
#                            data.frame(site="UTSW",    rate=0.90))
# site.sample.rates <- rbind(site.sample.rates, 
#                            data.frame(site="WISC",    rate=0.8))
# v.site.rate <- site.sample.rates$rate[site.sample.rates$site==dataset$site]
# site.sample.rates

# Set max sample size per 11-Mar BC conference call
#    - (target sample size - UTHSCSA ) / number of sites remaining
v.sample.max <- round((2000 - 129) / 8) 
message(paste0('Sample rate per site: ',v.sample.max))
```

### Loading query terms

```{r}
load("bc_terms_results.RData")
message('Number of terms loaded: ',nrow(bcterm$term204))
```

### Loading 'dataset' object

```{r}
input <- source('dataset.R')$value

conn.site <- input$conn

# about has $record_id $site name, $bc_db filename, $content_length, submitter $name, $issues_other
dataset <- input$about

message('Dataset identified: ',dataset$site)

```

### Loading patient data for `r dataset$site`

```{r}
tumor.site <- bc.exclusions(conn.site)
survey.sample <- check.cases(tumor.site)
survey.sample.size <- count.cases(survey.sample)

survey.sample$all.criteria <- reduce.logical(survey.sample)
```


```{r results='asis'}
ht(
  survey.sample.size[c('cum.pat'), ]
  )
```


### Applying exclusion criteria

```{r Identify eligible patients (pts not excluded),echo=TRUE}
# Get add'l fields for 'not excluded' pts
pat.not.excl <- 
  subset(unique(subset(tumor.site, 
                       select=c(patient_num,sex,vital,language,date.birth))),
                       patient_num %in% survey.sample$patient_num[survey.sample$all.criteria])

pat.not.excl$age <- round(age.in.years(pat.not.excl$date.birth))


# Handles sites that return multiple rows
# - MCRF and UIOWA can generate multiple rows
pat.not.excl$temp_placeholder <- c("<>")  # Work-around unique naming
pat.not.excl <- unique(pat.not.excl[,c("patient_num","temp_placeholder")])
v.eligible.pt.cnt <- nrow(pat.not.excl)
message('Number of eligible patients: ',v.eligible.pt.cnt)

head(pat.not.excl)
```

```{r echo=TRUE}
# v.sample.size <- min(v.eligible.pt.cnt,v.sample.max)
#randomized.pts.selected <- subset(pat.not.excl, 
#                                  patient_num %in% sample(pat.not.excl$patient_num,                             
#                                                          size=v.sample.size))
randomized.pts.selected <- pat.not.excl[sample(nrow(pat.not.excl)),]
message('Number of pts randomly sampled: ',nrow(randomized.pts.selected))

# Add row number
randomized.pts.selected$row_number <- 1:dim(randomized.pts.selected)[1]
randomized.pts.selected$redcap_record_id <- dataset$record_id
randomized.pts.selected$redcap_timestamp <- dataset$timestamp
randomized.pts.selected$randomized_timestamp <- Sys.time()
final.site.survey.set <- randomized.pts.selected[,c("row_number",
                                                    "patient_num",
                                                    "redcap_record_id",
                                                    "redcap_timestamp",
                                                    "randomized_timestamp")]
head(final.site.survey.set)
```

### Number of eligible patients randomly selected: `r nrow(final.site.survey.set)` out of `r v.eligible.pt.cnt`

```{r Send patient sampling to CSV file}
message(paste('Output directory: ',fetch$dataDir))
v.sample.filename <- paste0(dataset$site,"-",dataset$record_id,"-BC-deid-pt-sample.csv")
write.csv(final.site.survey.set, 
          file = file.path(fetch$dataDir,'/',v.sample.filename),
          row.names=FALSE)
message('Patient sample: ',v.sample.filename)
```